<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Address-alias</description>
   <name>Address_alias</name>
   <tag></tag>
   <elementGuidId>6b7323fa-8c76-4507-acc6-0dec4a070076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id=&quot;alias&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
