<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Address-home_phone</description>
   <name>Home_phone</name>
   <tag></tag>
   <elementGuidId>f31bc807-8b97-4c39-a0f9-7e1836da211c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id=&quot;phone&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
