<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Address-state</description>
   <name>State</name>
   <tag></tag>
   <elementGuidId>035f8f88-9a56-4a8f-bd17-0d5e0333cdaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[id=&quot;id_state&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
